const LOGIN = {
  FAILED_MESSAGE: 'E-FAI500',
  INVALID_ACCESS_TOKEN: 'E-IAT401',
  INVALID_REFRESH_TOKEN: 'E-IRT401',
  NOT_EXPIRED_TOKEN_YET: 'E-NET401',
  EXPIRED_TOKEN: 'E-EXT401',
  WRONG_TYPE_TOKEN: 'E-WTT401',
  WRONG_TYPE_SIGNATURE: 'E-WTS401',
  ACCESS_DENIED: 'E-ACD401',
  TOKEN_NOT_EXIST: 'E-TNE401',
  ALREADY_LOGIN_ACCOUNT: 'E-ALA400',
};

// eslint-disable-next-line import/prefer-default-export
export { LOGIN };
