name: baechelin-frontend-build
on: 
  push:                               # master Branch에서 pull_request,push 이벤트가 일어났을 때만 실행
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies    # 의존 파일 설치
        run: yarn install

      - name: Build                   # React Build
        env:
          CI: ""
        run: yarn build
        
      - name: Deploy                  # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://baechelin-frontend
